name: cbsoft
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Tássio Virgínio <email@example.com>

environment:
  # sdk: '>=2.1.0 <3.0.0'
  # sdk: '>=2.1.0 <2.1.2'
  sdk: '>=2.1.0 <2.5.1'

dependencies:
  angular: ^5.2.0
  angular_components: ^0.11.0
  translator: ^0.1.0+5
  intl: ^0.15.7
  angular_router: ^2.0.0-alpha+19
  ng_bootstrap: ^1.1.1

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.3.0 #^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.5.1
